### ISSUE TITLE
Handle expired token error

### ISSUE THREAD

**Issue by darrenkeen** [humaans/figbird#6]
Hi folks @Humaans! Loving figbird so far!

I have a question regrading how to handle auth expiry error. Usually I would have a helper function for requests that would handle it and do whats needed, but because this is a hook I cant do this.

Right now I am making my useFind request and then checking is error && error.message == "notAuthenticated" and pushing to an expiry page.

Whats the best way to do this?

Thanks.

**Comment by KidkArolis** [comment]
You might be able to do so in your feathers client setup (regardless of whether you're using websocket or rest, since feathers abstracts both the same way). This is what we do:

```js
import createFeathersClient from '@feathersjs/feathers'
import auth from '@feathersjs/authentication-client'
import socketio from '@feathersjs/socketio-client'
import io from 'socket.io-client'

export function createFeathers() {
  const socket = io()
  const feathers = createFeathersClient()
  feathers.configure(socketio(socket))
  feathers.configure(
    auth({
      storage: window.localStorage,
      storageKey: 'access-token',
      path: 'api/authentication',
      Authentication: AuthenticationClient,
    }),
  )

  feathers.hooks({
    before: {
      all: [],
    },
    error: {
      all: [handleUnauthenticated()],
    },
  })

  return feathers
}

class AuthenticationClient extends auth.AuthenticationClient {
  handleError(error, type) {
    if (error.code === 401 || error.code === 404) {
      const promise = this.removeAccessToken().then(() => this.reset())

      return type === 'logout'
        ? promise
        : promise.then(() => Promise.reject(error))
    }

    return Promise.reject(error)
  }
}

function handleUnauthenticated() {
  return context => {
    const { error } = context

    // The server is responding with 401s, that means the token is expired,
    // or invalid, etc.
    // The other case is when the socket is not connected, then we
    // do not want to reload the page, we just want to wait for the socket
    // to reconnect and reauthenticate, this is typically due to temporary
    // loss of server connection
    if (error.name === 'NotAuthenticated') {
      if (window.location.pathname !== '/login') {
        window.location.reload()
      }
    }
  }
}
```

There are 2 things relevant in the snippet above:

1. Customizing how `handleError` of Feathers `AuthenticationClient` handles the authentication error (e.g. handling 401s and 404s instead of the Feathers default 401 and 403).
2. **Most relevant to your question** - installing a client side error hook `handleUnauthenticated` which gets called on any failed requests. In our case we reload the page (which then redirects to the login page).

Let me know if this helps.

**Comment by darrenkeen** [comment]
This is awesome! Love the solution and the detailed answer is superb. Puts me on the right path!
